%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module AttributeCertificateVersion1-2009.

-ifndef(_ATTRIBUTECERTIFICATEVERSION1_2009_HRL_).
-define(_ATTRIBUTECERTIFICATEVERSION1_2009_HRL_, true).

-record('AttributeCertificateV1', {
  toBeSigned,
  algorithmIdentifier,
  signature
}).

-record('AttributeCertificateV1_algorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('AttributeCertificateInfoV1', {
  version = asn1_DEFAULT,
  subject,
  issuer,
  signature,
  serialNumber,
  attCertValidityPeriod,
  attributes,
  issuerUniqueID = asn1_NOVALUE,
  extensions = asn1_NOVALUE
}).

-record('AttributeCertificateInfoV1_signature', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('AttributeCertificateInfoV1_attributes_SEQOF', {
  type,
  values
}).

-record('AttributeCertificateInfoV1_extensions_SEQOF', {
  extnID,
  critical = asn1_DEFAULT,
  extnValue
}).

-endif. %% _ATTRIBUTECERTIFICATEVERSION1_2009_HRL_
