%% Generated by the Erlang ASN.1 compiler. Version: 5.4.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module CryptographicMessageSyntaxAlgorithms-2009.

-ifndef(_CRYPTOGRAPHICMESSAGESYNTAXALGORITHMS_2009_HRL_).
-define(_CRYPTOGRAPHICMESSAGESYNTAXALGORITHMS_2009_HRL_, true).

-record('KeyWrapAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('RC2CBCParameter', {
  rc2ParameterVersion,
  iv
}).

-record('PBKDF2-PRFsAlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('PBKDF2-SaltSourcesAlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('PBKDF2-params', {
  salt,
  iterationCount,
  keyLength = asn1_NOVALUE,
  prf = asn1_DEFAULT
}).

-define('id-alg-ESDH', {1,2,840,113549,1,9,16,3,5}).
-define('id-alg-SSDH', {1,2,840,113549,1,9,16,3,10}).
-define('id-alg-CMS3DESwrap', {1,2,840,113549,1,9,16,3,6}).
-define('id-alg-CMSRC2wrap', {1,2,840,113549,1,9,16,3,7}).
-define('des-ede3-cbc', {1,2,840,113549,3,7}).
-define('rc2-cbc', {1,2,840,113549,3,2}).
-define('hMAC-SHA1', {1,3,6,1,5,5,8,1,2}).
-define('id-PBKDF2', {1,2,840,113549,1,5,12}).
-define('defaultPBKDF2', {'PBKDF2-PRFsAlgorithmIdentifier',{1,3,6,1,5,5,8,1,2},'NULL'}).
-define('dh-public-number', {1,2,840,10046,2,1}).
-endif. %% _CRYPTOGRAPHICMESSAGESYNTAXALGORITHMS_2009_HRL_
