%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module DSS.

-ifndef(_DSS_HRL_).
-define(_DSS_HRL_, true).

-record('DSAPrivateKey', {
  version,
  p,
  q,
  g,
  y,
  x
}).

-endif. %% _DSS_HRL_
