%% Generated by the Erlang ASN.1 compiler. Version: 5.4.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module ECPrivateKey.

-ifndef(_ECPRIVATEKEY_HRL_).
-define(_ECPRIVATEKEY_HRL_, true).

-record('ECPrivateKey', {
  version,
  privateKey,
  parameters = asn1_NOVALUE,
  publicKey = asn1_NOVALUE,
  attributes = asn1_NOVALUE
}).

-endif. %% _ECPRIVATEKEY_HRL_
