%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module OTP-PKIX.

-ifndef(_OTP_PKIX_HRL_).
-define(_OTP_PKIX_HRL_, true).

-record('OTPCertificate', {
  tbsCertificate,
  signatureAlgorithm,
  signature
}).

-record('OTPCertificate_signatureAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('OTPTBSCertificate', {
  version = asn1_DEFAULT,
  serialNumber,
  signature,
  issuer,
  validity,
  subject,
  subjectPublicKeyInfo,
  %% with extensions
  issuerUniqueID = asn1_NOVALUE,
  subjectUniqueID = asn1_NOVALUE,
  extensions = asn1_NOVALUE
  %% end of extensions
}).

-record('OTPTBSCertificate_signature', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('OTPTBSCertificate_extensions_SEQOF', {
  extnID,
  critical = asn1_DEFAULT,
  extnValue
}).

-record('OTPRelativeDistinguishedName_SETOF', {
  type,
  value
}).

-record('HashSingleAttribute', {
  type,
  value
}).

-record('OTPPolicyInformation', {
  policyIdentifier,
  policyQualifiers = asn1_NOVALUE
}).

-record('OTPPolicyQualifierInfo', {
  policyQualifierId,
  qualifier
}).

-record('OTPUserNotice', {
  noticeRef = asn1_NOVALUE,
  explicitText = asn1_NOVALUE
}).

-record('OTPExtension', {
  extnID,
  critical = asn1_DEFAULT,
  extnValue
}).

-endif. %% _OTP_PKIX_HRL_
