%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKCS-3.

-ifndef(_PKCS_3_HRL_).
-define(_PKCS_3_HRL_, true).

-record('DHParameter', {
  prime,
  base,
  privateValueLength = asn1_NOVALUE
}).

-define('pkcs-3', {1,2,840,113549,1,3}).
-define('dhKeyAgreement', {1,2,840,113549,1,3,1}).
-endif. %% _PKCS_3_HRL_
