%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKIX-X400Address-2009.

-ifndef(_PKIX_X400ADDRESS_2009_HRL_).
-define(_PKIX_X400ADDRESS_2009_HRL_, true).

-record('ORAddress', {
  'built-in-standard-attributes',
  'built-in-domain-defined-attributes' = asn1_NOVALUE,
  'extension-attributes' = asn1_NOVALUE
}).

-record('BuiltInStandardAttributes', {
  'country-name' = asn1_NOVALUE,
  'administration-domain-name' = asn1_NOVALUE,
  'network-address' = asn1_NOVALUE,
  'terminal-identifier' = asn1_NOVALUE,
  'private-domain-name' = asn1_NOVALUE,
  'organization-name' = asn1_NOVALUE,
  'numeric-user-identifier' = asn1_NOVALUE,
  'personal-name' = asn1_NOVALUE,
  'organizational-unit-names' = asn1_NOVALUE
}).

-record('PersonalName', {
  surname,
  'given-name' = asn1_NOVALUE,
  initials = asn1_NOVALUE,
  'generation-qualifier' = asn1_NOVALUE
}).

-record('BuiltInDomainDefinedAttribute', {
  type,
  value
}).

-record('ExtensionAttribute', {
  'extension-attribute-type',
  'extension-attribute-value'
}).

-record('PDSParameter', {
  'printable-string' = asn1_NOVALUE,
  'teletex-string' = asn1_NOVALUE
}).

-record('PresentationAddress', {
  pSelector = asn1_NOVALUE,
  sSelector = asn1_NOVALUE,
  tSelector = asn1_NOVALUE,
  nAddresses
}).

-record('TeletexDomainDefinedAttribute', {
  type,
  value
}).

-define('ub-match', 128).
-define('ub-common-name-length', 64).
-define('ub-country-name-alpha-length', 2).
-define('ub-country-name-numeric-length', 3).
-define('ub-domain-defined-attributes', 4).
-define('ub-domain-defined-attribute-type-length', 8).
-define('ub-domain-defined-attribute-value-length', 128).
-define('ub-domain-name-length', 16).
-define('ub-extension-attributes', 256).
-define('ub-e163-4-number-length', 15).
-define('ub-e163-4-sub-address-length', 40).
-define('ub-generation-qualifier-length', 3).
-define('ub-given-name-length', 16).
-define('ub-initials-length', 5).
-define('ub-integer-options', 256).
-define('ub-numeric-user-id-length', 32).
-define('ub-organization-name-length', 64).
-define('ub-organizational-unit-name-length', 32).
-define('ub-organizational-units', 4).
-define('ub-pds-name-length', 16).
-define('ub-pds-parameter-length', 30).
-define('ub-pds-physical-address-lines', 6).
-define('ub-postal-code-length', 16).
-define('ub-surname-length', 40).
-define('ub-terminal-id-length', 24).
-define('ub-unformatted-address-length', 180).
-define('ub-x121-address-length', 16).
-endif. %% _PKIX_X400ADDRESS_2009_HRL_
