%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module PKIXAttributeCertificate-2009.

-ifndef(_PKIXATTRIBUTECERTIFICATE_2009_HRL_).
-define(_PKIXATTRIBUTECERTIFICATE_2009_HRL_, true).

-record('SecurityCategory-rfc3281', {
  type,
  value
}).

-record('AttributeCertificate', {
  toBeSigned,
  algorithmIdentifier,
  signature
}).

-record('AttributeCertificate_algorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('AttributeCertificateInfo', {
  version,
  holder,
  issuer,
  signature,
  serialNumber,
  attrCertValidityPeriod,
  attributes,
  issuerUniqueID = asn1_NOVALUE,
  extensions = asn1_NOVALUE
}).

-record('AttributeCertificateInfo_signature', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('AttributeCertificateInfo_attributes_SEQOF', {
  type,
  values
}).

-record('AttributeCertificateInfo_extensions_SEQOF', {
  extnID,
  critical = asn1_DEFAULT,
  extnValue
}).

-record('Holder', {
  baseCertificateID = asn1_NOVALUE,
  entityName = asn1_NOVALUE,
  objectDigestInfo = asn1_NOVALUE
}).

-record('ObjectDigestInfo', {
  digestedObjectType,
  otherObjectTypeID = asn1_NOVALUE,
  digestAlgorithm,
  objectDigest
}).

-record('ObjectDigestInfo_digestAlgorithm', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('V2Form', {
  issuerName = asn1_NOVALUE,
  baseCertificateID = asn1_NOVALUE,
  objectDigestInfo = asn1_NOVALUE
}).

-record('IssuerSerial', {
  issuer,
  serial,
  issuerUID = asn1_NOVALUE
}).

-record('AttCertValidityPeriod', {
  notBeforeTime,
  notAfterTime
}).

-record('TargetCert', {
  targetCertificate,
  targetName = asn1_NOVALUE,
  certDigestInfo = asn1_NOVALUE
}).

-record('AAControls', {
  pathLenConstraint = asn1_NOVALUE,
  permittedAttrs = asn1_NOVALUE,
  excludedAttrs = asn1_NOVALUE,
  permitUnSpecified = asn1_DEFAULT
}).

-record('IetfAttrSyntax', {
  policyAuthority = asn1_NOVALUE,
  values
}).

-record('SvceAuthInfo', {
  service,
  ident,
  authInfo = asn1_NOVALUE
}).

-record('RoleSyntax', {
  roleAuthority = asn1_NOVALUE,
  roleName
}).

-record('Clearance', {
  policyId,
  classList = asn1_DEFAULT,
  securityCategories = asn1_NOVALUE
}).

-record('Clearance_securityCategories_SETOF', {
  type,
  value
}).

-record('Clearance-rfc3281', {
  policyId,
  classList = asn1_DEFAULT,
  securityCategories = asn1_NOVALUE
}).

-record('Clearance-rfc3281_securityCategories_SETOF', {
  type,
  value
}).

-record('ACClearAttrs', {
  acIssuer,
  acSerial,
  attrs
}).

-record('ACClearAttrs_attrs_SEQOF', {
  type,
  values
}).

-define('id-pe-ac-auditIdentity', {1,3,6,1,5,5,7,1,4}).
-define('id-pe-aaControls', {1,3,6,1,5,5,7,1,6}).
-define('id-pe-ac-proxying', {1,3,6,1,5,5,7,1,10}).
-define('id-ce-targetInformation', {2,5,29,55}).
-define('id-ce-noRevAvail', {2,5,29,56}).
-define('id-aca', {1,3,6,1,5,5,7,10}).
-define('id-aca-authenticationInfo', {1,3,6,1,5,5,7,10,1}).
-define('id-aca-accessIdentity', {1,3,6,1,5,5,7,10,2}).
-define('id-aca-chargingIdentity', {1,3,6,1,5,5,7,10,3}).
-define('id-aca-group', {1,3,6,1,5,5,7,10,4}).
-define('id-aca-encAttrs', {1,3,6,1,5,5,7,10,6}).
-define('id-at-role', {2,5,4,72}).
-define('id-at-clearance', {2,5,4,55}).
-define('id-at-clearance-rfc3281', {2,5,1,5,55}).
-endif. %% _PKIXATTRIBUTECERTIFICATE_2009_HRL_
