%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module Safecurves-pkix-18.

-ifndef(_SAFECURVES_PKIX_18_HRL_).
-define(_SAFECURVES_PKIX_18_HRL_, true).

-record('kaa-X25519_AlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-record('kaa-X448_AlgorithmIdentifier', {
  algorithm,
  parameters = asn1_NOVALUE
}).

-define('id-edwards-curve-algs', {1,3,101}).
-define('id-X25519', {1,3,101,110}).
-define('id-X448', {1,3,101,111}).
-define('id-Ed25519', {1,3,101,112}).
-define('id-Ed448', {1,3,101,113}).
-endif. %% _SAFECURVES_PKIX_18_HRL_
