%% Generated by the Erlang ASN.1 compiler. Version: 5.4.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module SecureMimeMessageV3dot1-2009.

-ifndef(_SECUREMIMEMESSAGEV3DOT1_2009_HRL_).
-define(_SECUREMIMEMESSAGEV3DOT1_2009_HRL_, true).

-record('aa-smimeCapabilities_SMIMECapabilities_SEQOF', {
  capabilityID,
  parameters = asn1_NOVALUE
}).

-define('id-aa', {1,2,840,113549,1,9,16,2}).
-define('smimeCapabilities', {1,2,840,113549,1,9,15}).
-define('id-aa-encrypKeyPref', {1,2,840,113549,1,9,16,2,11}).
-define('id-smime', {1,2,840,113549,1,9,16}).
-define('id-cap', {1,2,840,113549,1,9,16,11}).
-define('id-cap-preferBinaryInside', {1,2,840,113549,1,9,16,11,1}).
-endif. %% _SECUREMIMEMESSAGEV3DOT1_2009_HRL_
