%% Generated by the Erlang ASN.1 compiler. Version: 5.4.3
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module SLH-DSA-Module-2024.

-ifndef(_SLH_DSA_MODULE_2024_HRL_).
-define(_SLH_DSA_MODULE_2024_HRL_, true).

-define('nistAlgorithms', {2,16,840,1,101,3,4}).
-define('sigAlgs', {2,16,840,1,101,3,4,3}).
-define('id-slh-dsa-sha2-128s', {2,16,840,1,101,3,4,3,20}).
-define('id-slh-dsa-sha2-128f', {2,16,840,1,101,3,4,3,21}).
-define('id-slh-dsa-sha2-192s', {2,16,840,1,101,3,4,3,22}).
-define('id-slh-dsa-sha2-192f', {2,16,840,1,101,3,4,3,23}).
-define('id-slh-dsa-sha2-256s', {2,16,840,1,101,3,4,3,24}).
-define('id-slh-dsa-sha2-256f', {2,16,840,1,101,3,4,3,25}).
-define('id-slh-dsa-shake-128s', {2,16,840,1,101,3,4,3,26}).
-define('id-slh-dsa-shake-128f', {2,16,840,1,101,3,4,3,27}).
-define('id-slh-dsa-shake-192s', {2,16,840,1,101,3,4,3,28}).
-define('id-slh-dsa-shake-192f', {2,16,840,1,101,3,4,3,29}).
-define('id-slh-dsa-shake-256s', {2,16,840,1,101,3,4,3,30}).
-define('id-slh-dsa-shake-256f', {2,16,840,1,101,3,4,3,31}).
-endif. %% _SLH_DSA_MODULE_2024_HRL_
