%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module X509-ML-DSA-2025.

-ifndef(_X509_ML_DSA_2025_HRL_).
-define(_X509_ML_DSA_2025_HRL_, true).

-record('ML-DSA-44-PrivateKey_both', {
  seed,
  expandedKey
}).

-record('ML-DSA-65-PrivateKey_both', {
  seed,
  expandedKey
}).

-record('ML-DSA-87-PrivateKey_both', {
  seed,
  expandedKey
}).

-define('nistAlgorithms', {2,16,840,1,101,3,4}).
-define('sigAlgs', {2,16,840,1,101,3,4,3}).
-define('id-ml-dsa-44', {2,16,840,1,101,3,4,3,17}).
-define('id-ml-dsa-65', {2,16,840,1,101,3,4,3,18}).
-define('id-ml-dsa-87', {2,16,840,1,101,3,4,3,19}).
-endif. %% _X509_ML_DSA_2025_HRL_
