%% Generated by the Erlang ASN.1 compiler. Version: 5.5
%% Purpose: Erlang record definitions for each named and unnamed
%% SEQUENCE and SET, and macro definitions for each value
%% definition in module X509-ML-KEM-2025.

-ifndef(_X509_ML_KEM_2025_HRL_).
-define(_X509_ML_KEM_2025_HRL_, true).

-record('ML-KEM-512-PrivateKey_both', {
  seed,
  expandedKey
}).

-record('ML-KEM-768-PrivateKey_both', {
  seed,
  expandedKey
}).

-record('ML-KEM-1024-PrivateKey_both', {
  seed,
  expandedKey
}).

-define('nistAlgorithms', {2,16,840,1,101,3,4}).
-define('kems', {2,16,840,1,101,3,4,4}).
-define('id-alg-ml-kem-512', {2,16,840,1,101,3,4,4,1}).
-define('id-alg-ml-kem-768', {2,16,840,1,101,3,4,4,2}).
-define('id-alg-ml-kem-1024', {2,16,840,1,101,3,4,4,3}).
-endif. %% _X509_ML_KEM_2025_HRL_
